export class shippereResponse {
    shipperId:number
    shipperName:string
    shipperAddress:string;
    ContactNo:string;
    emailAddress:string;
    mobileNo:string;
    isDeleted:string;
    airportName:string;
    regionName:string;
    countryName:string;
    cityName:string;
    countryID:number;
    stateID:number;
    cityID:number;
    CNIC:string;
}
export class requestShipper {
    shipperId:string;
    isNew:boolean=false;
    shipperName:string;
    shipperAddress:string;
    countryID:string;
    stateID:string;
    cityID:string;
    CNIC:string;
    ContactNo:string;
    emailAddress:string;
    faxNo:string;
    mobileNo:string;
    }